"""Colophon package."""

from .coordination import (
    BookCoordinationAgent,
    ChapterCoordinationAgent,
    MessageBus,
    ParagraphCoordinationAgent,
    SectionCoordinationAgent,
)
from .agent_skills import AgentSkill, AgentSkillActivation, AgentSkillsRuntime, AgentSkillValidationIssue
from .agents import OutlineExpanderAgent
from .kg_update import KGUpdateConfig, KnowledgeGraphGeneratorUpdater
from .llm import LLMConfig, create_llm_client
from .functional_forms import SoftValidationFinding, SoftValidationResult, run_soft_validation, select_functional_form
from .genre_ontology import build_genre_ontology_context
from .writing_ontology import (
    WritingOntologyValidationFinding,
    WritingOntologyValidationResult,
    build_writing_ontology_context,
    run_writing_ontology_validation,
)
from .note_import import NotesImportConfig, NotesImportResult, NotesKnowledgeGraphImporter
from .io import InputArtifacts, resolve_input_artifacts
from .user_input import (
    AgentSDKUserInputHandler,
    CODEX_ASK_USER_QUESTION_TOOL_NAME,
    GUIDANCE_STAGE_COORDINATION,
    GUIDANCE_STAGE_OUTLINE,
    GUIDANCE_STAGE_PLANNING,
    GUIDANCE_STAGE_RECOMMENDATIONS,
    GUIDANCE_STAGES_SUPPORTED,
    OpenAICodexUserInputHandler,
    CoordinationGuidance,
    OutlineGuidance,
    PlanningGuidance,
    RecommendationGuidance,
    UserGuidanceBundle,
    apply_coordination_guidance,
    apply_guidance_to_pipeline_flags,
    apply_outline_guidance,
    apply_recommendation_guidance,
    build_codex_ask_user_question_tool,
    build_coordination_breakdown_questionnaire,
    build_coordination_questionnaire,
    build_outline_questionnaire,
    build_planning_guidance_prompt,
    build_planning_questionnaire,
    build_recommendation_questionnaire,
    build_stage_questionnaire,
    collect_user_answers,
    collect_stage_guidance,
    collect_user_guidance_bundle,
    infer_coordination_guidance,
    infer_outline_guidance,
    infer_recommendation_guidance,
    infer_planning_guidance,
    normalize_guidance_stages,
    request_planning_guidance_via_openai_codex,
    request_planning_guidance_via_agent_sdk,
)
from .models import (
    Chapter,
    Claim,
    CoordinationMessage,
    Figure,
    GapRequest,
    Manuscript,
    Paragraph,
    RecommendationProposal,
    Section,
    Source,
)
from .ontology import (
    normalize_functional_forms_catalog,
    normalize_genre_ontology,
    normalize_writing_companion_ontology,
)
from .pipeline import ColophonPipeline, PipelineConfig
from .recommendations import (
    OpenAlexSearchClient,
    PaperRecommendationWorkflow,
    RecommendationConfig,
    SemanticScholarSearchClient,
)
from .vectors import EmbeddingConfig, InMemoryVectorDB, create_embedding_client

__all__ = [
    "BookCoordinationAgent",
    "AgentSkill",
    "AgentSkillActivation",
    "AgentSkillValidationIssue",
    "AgentSkillsRuntime",
    "Chapter",
    "ChapterCoordinationAgent",
    "Claim",
    "ColophonPipeline",
    "CoordinationMessage",
    "EmbeddingConfig",
    "Figure",
    "GapRequest",
    "InMemoryVectorDB",
    "InputArtifacts",
    "KGUpdateConfig",
    "CODEX_ASK_USER_QUESTION_TOOL_NAME",
    "GUIDANCE_STAGE_PLANNING",
    "GUIDANCE_STAGE_RECOMMENDATIONS",
    "GUIDANCE_STAGE_OUTLINE",
    "GUIDANCE_STAGE_COORDINATION",
    "GUIDANCE_STAGES_SUPPORTED",
    "KnowledgeGraphGeneratorUpdater",
    "LLMConfig",
    "MessageBus",
    "Manuscript",
    "NotesImportConfig",
    "NotesImportResult",
    "NotesKnowledgeGraphImporter",
    "OpenAlexSearchClient",
    "OpenAICodexUserInputHandler",
    "OutlineExpanderAgent",
    "OutlineGuidance",
    "PlanningGuidance",
    "PaperRecommendationWorkflow",
    "ParagraphCoordinationAgent",
    "Paragraph",
    "PipelineConfig",
    "RecommendationConfig",
    "RecommendationGuidance",
    "RecommendationProposal",
    "SemanticScholarSearchClient",
    "Section",
    "SectionCoordinationAgent",
    "SoftValidationFinding",
    "SoftValidationResult",
    "Source",
    "UserGuidanceBundle",
    "CoordinationGuidance",
    "create_embedding_client",
    "build_writing_ontology_context",
    "normalize_functional_forms_catalog",
    "normalize_genre_ontology",
    "normalize_writing_companion_ontology",
    "build_genre_ontology_context",
    "build_codex_ask_user_question_tool",
    "build_coordination_breakdown_questionnaire",
    "build_coordination_questionnaire",
    "build_outline_questionnaire",
    "build_planning_guidance_prompt",
    "build_planning_questionnaire",
    "build_recommendation_questionnaire",
    "build_stage_questionnaire",
    "create_llm_client",
    "collect_user_answers",
    "collect_stage_guidance",
    "collect_user_guidance_bundle",
    "infer_coordination_guidance",
    "infer_outline_guidance",
    "infer_recommendation_guidance",
    "infer_planning_guidance",
    "normalize_guidance_stages",
    "apply_coordination_guidance",
    "apply_guidance_to_pipeline_flags",
    "apply_outline_guidance",
    "apply_recommendation_guidance",
    "request_planning_guidance_via_openai_codex",
    "request_planning_guidance_via_agent_sdk",
    "run_writing_ontology_validation",
    "resolve_input_artifacts",
    "run_soft_validation",
    "select_functional_form",
    "AgentSDKUserInputHandler",
    "WritingOntologyValidationFinding",
    "WritingOntologyValidationResult",
]
