"""Core data models for manuscript structure, coordination, and recommendations."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass(slots=True)
class Source:
    """Bibliographic source with text content available for retrieval."""

    id: str
    title: str
    authors: list[str]
    year: int | None
    text: str
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(slots=True)
class Figure:
    """Figure/image artifact that can be referenced in generated narratives."""

    id: str
    caption: str
    uri: str = ""
    alt_text: str = ""
    related_entities: list[str] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(slots=True)
class CoordinationMessage:
    """Message passed between coordination/editing agents across hierarchy levels."""

    sender: str
    receiver: str
    message_type: str
    content: str
    related_id: str = ""
    priority: str = "normal"


@dataclass(slots=True)
class GapRequest:
    """Request surfaced when bibliography/graph/outline context is insufficient."""

    level: str
    component: str
    request: str
    rationale: str
    related_id: str = ""


@dataclass(slots=True)
class RecommendationProposal:
    """Proposed paper addition with suggested bibliography and KG updates."""

    proposal_id: str
    title: str
    authors: list[str]
    publication: str
    year: int | None
    abstract: str
    citation_count: int
    source_url: str
    doi: str
    score: float
    reasons: list[str] = field(default_factory=list)
    based_on_source_ids: list[str] = field(default_factory=list)
    bibliography_entry: dict[str, Any] = field(default_factory=dict)
    knowledge_graph_update: dict[str, Any] = field(default_factory=dict)


@dataclass(slots=True)
class Claim:
    """Atomic factual statement generated by the claim-writing agent."""

    id: str
    text: str
    evidence_ids: list[str] = field(default_factory=list)
    figure_ids: list[str] = field(default_factory=list)


@dataclass(slots=True)
class Paragraph:
    """A paragraph generated from one or more claims."""

    id: str
    text: str
    claim_ids: list[str] = field(default_factory=list)


@dataclass(slots=True)
class Section:
    """A section in a chapter."""

    id: str
    title: str
    paragraphs: list[Paragraph] = field(default_factory=list)
    claims: list[Claim] = field(default_factory=list)
    figures: list[Figure] = field(default_factory=list)


@dataclass(slots=True)
class Chapter:
    """A manuscript chapter composed of sections."""

    id: str
    title: str
    sections: list[Section] = field(default_factory=list)


@dataclass(slots=True)
class Manuscript:
    """Final manuscript output and generation diagnostics."""

    title: str
    chapters: list[Chapter] = field(default_factory=list)
    diagnostics: dict[str, Any] = field(default_factory=dict)
    coordination_messages: list[CoordinationMessage] = field(default_factory=list)
    gap_requests: list[GapRequest] = field(default_factory=list)
    recommendation_proposals: list[RecommendationProposal] = field(default_factory=list)

    def to_markdown(self) -> str:
        """To markdown.

        Returns
        -------
        str
            Return value description.
        """
        lines: list[str] = [f"# {self.title}", ""]
        for chapter in self.chapters:
            lines.append(f"## {chapter.title}")
            lines.append("")
            for section in chapter.sections:
                lines.append(f"### {section.title}")
                lines.append("")
                for paragraph in section.paragraphs:
                    lines.append(paragraph.text)
                    lines.append("")
                if section.figures:
                    lines.append("#### Figures")
                    lines.append("")
                    for figure in section.figures:
                        lines.append(_figure_markdown_line(figure))
                    lines.append("")
        lines.extend(_append_recommendations_markdown(self.recommendation_proposals))
        lines.extend(_append_gap_requests_markdown(self.gap_requests))
        return "\n".join(lines).strip() + "\n"

    def to_plain_text(self) -> str:
        """To plain text.

        Returns
        -------
        str
            Return value description.
        """
        lines: list[str] = [self.title, "=" * len(self.title), ""]
        for chapter in self.chapters:
            lines.append(f"Chapter: {chapter.title}")
            lines.append("")
            for section in chapter.sections:
                lines.append(f"Section: {section.title}")
                lines.append("")
                for paragraph in section.paragraphs:
                    lines.append(paragraph.text)
                    lines.append("")
                if section.figures:
                    lines.append("Figures:")
                    for figure in section.figures:
                        lines.append(_figure_text_line(figure))
                    lines.append("")
        lines.extend(_append_recommendations_text(self.recommendation_proposals))
        lines.extend(_append_gap_requests_text(self.gap_requests))
        return "\n".join(lines).strip() + "\n"

    def to_rst(self) -> str:
        """To rst.

        Returns
        -------
        str
            Return value description.
        """
        lines: list[str] = [self.title, "=" * len(self.title), ""]
        for chapter in self.chapters:
            lines.append(chapter.title)
            lines.append("-" * len(chapter.title))
            lines.append("")
            for section in chapter.sections:
                lines.append(section.title)
                lines.append("~" * len(section.title))
                lines.append("")
                for paragraph in section.paragraphs:
                    lines.append(paragraph.text)
                    lines.append("")
                if section.figures:
                    lines.append("Figures")
                    lines.append("^" * len("Figures"))
                    lines.append("")
                    for figure in section.figures:
                        lines.append(_figure_text_line(figure))
                    lines.append("")
        lines.extend(_append_recommendations_rst(self.recommendation_proposals))
        lines.extend(_append_gap_requests_rst(self.gap_requests))
        return "\n".join(lines).strip() + "\n"

    def to_latex(self) -> str:
        """To latex.

        Returns
        -------
        str
            Return value description.
        """
        lines: list[str] = [
            "\\documentclass{article}",
            "\\usepackage[utf8]{inputenc}",
            f"\\title{{{_latex_escape(self.title)}}}",
            "\\begin{document}",
            "\\maketitle",
            "",
        ]
        for chapter in self.chapters:
            lines.append(f"\\section{{{_latex_escape(chapter.title)}}}")
            for section in chapter.sections:
                lines.append(f"\\subsection{{{_latex_escape(section.title)}}}")
                for paragraph in section.paragraphs:
                    lines.append(_latex_escape(paragraph.text))
                    lines.append("")
                if section.figures:
                    lines.append("\\paragraph{Figures}")
                    for figure in section.figures:
                        lines.append(_latex_escape(_figure_text_line(figure)))
                    lines.append("")
        lines.extend(_append_recommendations_latex(self.recommendation_proposals))
        lines.extend(_append_gap_requests_latex(self.gap_requests))
        lines.append("\\end{document}")
        return "\n".join(lines).strip() + "\n"

    def to_rtf(self) -> str:
        """To rtf.

        Returns
        -------
        str
            Return value description.
        """
        plain = self.to_plain_text().rstrip("\n")
        escaped = _rtf_escape(plain).replace("\n", "\\par\n")
        return "{\\rtf1\\ansi\n" + escaped + "\\par\n}\n"

    def render(self, output_format: str) -> str:
        """Render.

        Parameters
        ----------
        output_format : str
            Parameter description.

        Returns
        -------
        str
            Return value description.
        """
        normalized = output_format.strip().lower()
        if normalized == "markdown":
            return self.to_markdown()
        if normalized == "text":
            return self.to_plain_text()
        if normalized == "rst":
            return self.to_rst()
        if normalized == "latex":
            return self.to_latex()
        if normalized == "rtf":
            return self.to_rtf()
        raise ValueError(f"Unsupported output format: {output_format}")


def _latex_escape(value: str) -> str:
    """Latex escape.

    Parameters
    ----------
    value : str
        Parameter description.

    Returns
    -------
    str
        Return value description.
    """
    escape_map = {
        "\\": "\\textbackslash{}",
        "{": "\\{",
        "}": "\\}",
        "$": "\\$",
        "&": "\\&",
        "#": "\\#",
        "_": "\\_",
        "%": "\\%",
        "~": "\\textasciitilde{}",
        "^": "\\textasciicircum{}",
    }
    return "".join(escape_map.get(char, char) for char in value)


def _rtf_escape(value: str) -> str:
    """Rtf escape.

    Parameters
    ----------
    value : str
        Parameter description.

    Returns
    -------
    str
        Return value description.
    """
    return value.replace("\\", "\\\\").replace("{", "\\{").replace("}", "\\}")


def _figure_markdown_line(figure: Figure) -> str:
    """Figure markdown line.

    Parameters
    ----------
    figure : Figure
        Parameter description.

    Returns
    -------
    str
        Return value description.
    """
    if figure.uri:
        return f"- Figure {figure.id}: {figure.caption} ({figure.uri})"
    return f"- Figure {figure.id}: {figure.caption}"


def _figure_text_line(figure: Figure) -> str:
    """Figure text line.

    Parameters
    ----------
    figure : Figure
        Parameter description.

    Returns
    -------
    str
        Return value description.
    """
    if figure.uri:
        return f"- Figure {figure.id}: {figure.caption} [{figure.uri}]"
    return f"- Figure {figure.id}: {figure.caption}"


def _append_gap_requests_markdown(gaps: list[GapRequest]) -> list[str]:
    """Append gap requests markdown.

    Parameters
    ----------
    gaps : list[GapRequest]
        Parameter description.

    Returns
    -------
    list[str]
        Return value description.
    """
    if not gaps:
        return []
    lines = ["## Gap Requests", ""]
    for gap in gaps:
        scope = f"[{gap.level}/{gap.component}]"
        related = f" ({gap.related_id})" if gap.related_id else ""
        lines.append(f"- {scope} {gap.request}{related}: {gap.rationale}")
    lines.append("")
    return lines


def _append_recommendations_markdown(recommendations: list[RecommendationProposal]) -> list[str]:
    """Append recommendations markdown.

    Parameters
    ----------
    recommendations : list[RecommendationProposal]
        Parameter description.

    Returns
    -------
    list[str]
        Return value description.
    """
    if not recommendations:
        return []
    lines = ["## Recommended Papers", ""]
    for proposal in recommendations:
        lines.append(
            f"- **{proposal.title}** ({proposal.year or 'n.d.'}), score={proposal.score:.3f}, "
            f"citations={proposal.citation_count}"
        )
        if proposal.publication:
            lines.append(f"  - Publication: {proposal.publication}")
        if proposal.authors:
            lines.append(f"  - Authors: {', '.join(proposal.authors)}")
        if proposal.reasons:
            lines.append(f"  - Why: {'; '.join(proposal.reasons)}")
        if proposal.source_url:
            lines.append(f"  - Link: {proposal.source_url}")
        lines.append(f"  - Bibliography proposal id: {proposal.bibliography_entry.get('id', proposal.proposal_id)}")
        lines.append(
            f"  - KG update: {len(proposal.knowledge_graph_update.get('entities', []))} entities, "
            f"{len(proposal.knowledge_graph_update.get('relations', []))} relations"
        )
    lines.append("")
    return lines


def _append_gap_requests_text(gaps: list[GapRequest]) -> list[str]:
    """Append gap requests text.

    Parameters
    ----------
    gaps : list[GapRequest]
        Parameter description.

    Returns
    -------
    list[str]
        Return value description.
    """
    if not gaps:
        return []
    lines = ["Gap Requests:", ""]
    for gap in gaps:
        scope = f"[{gap.level}/{gap.component}]"
        related = f" ({gap.related_id})" if gap.related_id else ""
        lines.append(f"- {scope} {gap.request}{related}: {gap.rationale}")
    lines.append("")
    return lines


def _append_recommendations_text(recommendations: list[RecommendationProposal]) -> list[str]:
    """Append recommendations text.

    Parameters
    ----------
    recommendations : list[RecommendationProposal]
        Parameter description.

    Returns
    -------
    list[str]
        Return value description.
    """
    if not recommendations:
        return []
    lines = ["Recommended Papers:", ""]
    for proposal in recommendations:
        lines.append(
            f"- {proposal.title} ({proposal.year or 'n.d.'}), score={proposal.score:.3f}, citations={proposal.citation_count}"
        )
        if proposal.publication:
            lines.append(f"  Publication: {proposal.publication}")
        if proposal.reasons:
            lines.append(f"  Why: {'; '.join(proposal.reasons)}")
        if proposal.source_url:
            lines.append(f"  Link: {proposal.source_url}")
    lines.append("")
    return lines


def _append_gap_requests_rst(gaps: list[GapRequest]) -> list[str]:
    """Append gap requests rst.

    Parameters
    ----------
    gaps : list[GapRequest]
        Parameter description.

    Returns
    -------
    list[str]
        Return value description.
    """
    if not gaps:
        return []
    lines = ["Gap Requests", "^^^^^^^^^^^^", ""]
    for gap in gaps:
        scope = f"[{gap.level}/{gap.component}]"
        related = f" ({gap.related_id})" if gap.related_id else ""
        lines.append(f"- {scope} {gap.request}{related}: {gap.rationale}")
    lines.append("")
    return lines


def _append_recommendations_rst(recommendations: list[RecommendationProposal]) -> list[str]:
    """Append recommendations rst.

    Parameters
    ----------
    recommendations : list[RecommendationProposal]
        Parameter description.

    Returns
    -------
    list[str]
        Return value description.
    """
    if not recommendations:
        return []
    lines = ["Recommended Papers", "^^^^^^^^^^^^^^^^^^", ""]
    for proposal in recommendations:
        lines.append(
            f"- {proposal.title} ({proposal.year or 'n.d.'}), score={proposal.score:.3f}, citations={proposal.citation_count}"
        )
        if proposal.publication:
            lines.append(f"  Publication: {proposal.publication}")
        if proposal.reasons:
            lines.append(f"  Why: {'; '.join(proposal.reasons)}")
        if proposal.source_url:
            lines.append(f"  Link: {proposal.source_url}")
    lines.append("")
    return lines


def _append_gap_requests_latex(gaps: list[GapRequest]) -> list[str]:
    """Append gap requests latex.

    Parameters
    ----------
    gaps : list[GapRequest]
        Parameter description.

    Returns
    -------
    list[str]
        Return value description.
    """
    if not gaps:
        return []
    lines = ["\\section*{Gap Requests}"]
    for gap in gaps:
        scope = f"[{gap.level}/{gap.component}]"
        related = f" ({gap.related_id})" if gap.related_id else ""
        line = f"- {scope} {gap.request}{related}: {gap.rationale}"
        lines.append(_latex_escape(line))
    lines.append("")
    return lines


def _append_recommendations_latex(recommendations: list[RecommendationProposal]) -> list[str]:
    """Append recommendations latex.

    Parameters
    ----------
    recommendations : list[RecommendationProposal]
        Parameter description.

    Returns
    -------
    list[str]
        Return value description.
    """
    if not recommendations:
        return []
    lines = ["\\section*{Recommended Papers}"]
    for proposal in recommendations:
        line = (
            f"- {proposal.title} ({proposal.year or 'n.d.'}), "
            f"score={proposal.score:.3f}, citations={proposal.citation_count}"
        )
        lines.append(_latex_escape(line))
        if proposal.source_url:
            lines.append(_latex_escape(f"  Link: {proposal.source_url}"))
    lines.append("")
    return lines
